
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.StyleCop
{
	public partial class Spelling
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.StyleCop.Spelling
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.StyleCop.Spelling";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
